#!/bin/bash

# Install nginx
apt-get update
apt-get install -y nginx

# Change nginx user and group
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/g' /etc/nginx/nginx.conf

# Update nginx configuration to listen on port 8080
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default

# Restart nginx service
systemctl restart nginx
