#!/usr/bin/env bash
# Set the key name and number of bits
key_name="school"
key_bits=4096

# Generate the key pair with a passphrase
ssh-keygen -t rsa -b "$key_bits" -f "$key_name" -N "betty"

echo "Key pair created with the following details:"
echo "Public key: $key_name.pub"
echo "Private key: $key_name"
